Only manage mute state if audible or already muted
igorlogius/mute-unfocused-tabs pull request #7
Opened 2023-08-01 01:53 UTC by robbiebowman

# Purpose
This attempts to reduce the number of immediate uninstalls for first time users.

It's quite jarring to install Mute Unfocused Tabs and suddenly have every tab given the `MUTED` tag. I think some users would see it as too invasive and reflexively uninstall the extension, despite it doing exactly what it says on the tin.

# Changelog
- Only sets mute state for tabs that are either audible or already muted
- Updates tab mute state on all tab updates. For example, if a tab becomes audible

# Details
Me again. Addressing this old issue: https://github.com/igorlogius/mute-unfocused-tabs/issues/3

I think it's a fair request. We have both the property to check for audible state and an event listener for when that property changes.

Here's a demo of it in action:

https://github.com/igorlogius/mute-unfocused-tabs/assets/13639947/66a27149-d71c-4d29-a6ed-be2210ceb8f9

# Gotchas
The `audible` state of a tab is overridden by its `muted` state. This means a couple of seconds after a tab is muted, it will have `audible == false` regardless of whether sound would play if we unmuted.

This means that if, for example, a song finishes in an unfocused, muted tab, `audible` won't change state. The tab will remain muted until another listener affects it (for example, the user focuses the tab).

I don't see this as an issue, just thought you should know.

2023-08-01 07:26 UTC, igorlogius commented
I remember the last time i tried this, i had audio issues which i found very very annoying if not all tabs where muted, ... i will try it again with your PR, but if those issues are still present i am not sure i want to merge it like this. In that case, i could still see to add  this feature as switchable option. Then users could then decide if he/she wants to enable it or not. 

But first i'm gonna try it out later and see if anything changed. Be back later.

2023-08-01 12:30 UTC, igorlogius commented
I cant seem to reproduce the original audio issue i had a while back with #3 so no issue here. 
But i like to think and experiment a little on the Gotcha you described. 
I'll be back later.

2023-08-01 14:04 UTC, igorlogius requested changes
review 1

2023-08-03 22:02 UTC, igorlogius commented
Also ... 

> This attempts to reduce the number of immediate uninstalls for first time users.

:rofl: 

i never even considert anyone could be this annoyed by it. 
Had mozilla not increased the tab height and keeped the old unmute icon ... i think most people would never even havenoticed it.

2023-08-06 19:57 UTC, robbiebowman commented on background.js
> +  browser.tabs.onUpdated.addListener(updateMuteState);
Excellent point. Applied that change.

2023-08-06 19:57 UTC, robbiebowman commented
Apologies for the delay, was busy. Implemented the two changes you suggested.

2023-08-07 07:01 UTC, igorlogius commented
@robbiebowman 

Looks good so far ... but i have some doubt about: 

` || tab.mutedInfo.muted) {`

which seems to prevent a user from muting the currently focused tab.

It kind of seems like a bad idea to deny/cancel a explicit user input like that.

2023-08-07 19:12 UTC, igorlogius requested changes

2023-08-07 19:12 UTC, igorlogius commented on background.js
> +        if (tab.audible || tab.mutedInfo.muted) {
I dont really see a good way to fix this without undoing the other functionality.
But if you think you know a way, let me no, but if not i am terriblily sorry, but i'll have to reject the PR.

2023-08-07 21:42 UTC, igorlogius commented on background.js
> +        if (tab.audible || tab.mutedInfo.muted) {
Another idea would be to add this behaviour as a switch/option to enable
If you think that people might prefer it. 
I just wouldn't want to make it the default for now.

2023-08-07 21:49 UTC, robbiebowman commented on background.js
> +        if (tab.audible || tab.mutedInfo.muted) {
> I am not sure about || tab.mutedInfo.muted ... since it denies a user to mute the currently focused tab.

I don't actually see this as a huge issue as the behaviour is pretty similar to the current state. i.e. once the user moves away from the current tab, it will forget that they manually muted that tab.

I agree neither state is desirable. Maybe we should roll this into the other feature of manual muting controlling whether the tab is in `_taggedManually`. I'll continue playing around to see if I can make it behave intuitively.

2023-08-07 22:10 UTC, igorlogius commented on background.js
> +        if (tab.audible || tab.mutedInfo.muted) {
Sorry, but unexpectedly blocking a user action is in my book a no small issue.  

> Maybe we should roll this into the other feature of manual muting controlling whether the tab is in _taggedManually

That seems to make things even more confusing / unclear, but if you think you can find an intuitive way to handle all the states, i'll take a look at your suggestion, otherwise the option of making this behaviour a second operation mode still stands.

2023-08-12 01:42 UTC, robbiebowman commented
Spent a while trying to toggle the management state when the user clicked mute/unmute, but couldn't get anything good.

Going to close this.

2023-08-12 01:42 UTC, closed without merging

2023-08-12 07:30 UTC, igorlogius commented
Not just being able to approve and merge this PR makes me feel bad about not correctly working though your last one - Totally my fault. - I am really sorry about that, which is why i want to thank you here again for the time you spend to help and try to improve this addon. 

So, "Thank you!"

As a Sidenote:  With the recent annoucement of mozilla to open the addon space to android again ... there might be future opportunities to make other improvments, and i am sure if you are still interested we'll be able to get you on the contributors list. 

So for now i'll just be saying: "See you later, and stay well!"